SELECT invoice_id, branch, city, category, unit_price, quantity, "date", "time", payment_method, rating, profit_margin, total
FROM public.walmart;



## 🛒 Walmart Analytics — Business Questions & Objectives

This SQL project focuses on exploring key business insights from Walmart store transaction data.  
Each analytical question is designed to uncover patterns in customer behavior, operational efficiency, and product performance.

---

### **1️⃣ Payment Methods & Sales Analysis**
- **Question:** What payment methods were used, and how many transactions and items were sold using each?
- **Purpose:** Understand customer payment preferences to optimize payment systems and streamline checkout experiences.

---

### **2️⃣ Highest Rated Category by Branch**
- **Question:** Which product category received the highest average customer rating in each branch?
- **Purpose:** Identify customer favorites and support strategic promotion or inventory allocation per branch.

---

### **3️⃣ Busiest Day per Branch**
- **Question:** What day of the week sees the highest transaction volume in each branch?
- **Purpose:** Improve staffing schedules and inventory planning to handle peak shopping days efficiently.

---

### **4️⃣ Quantity Sold by Payment Method**
- **Question:** How many total items were purchased using each payment method?
- **Purpose:** Track how purchasing behavior correlates with payment types to improve transaction strategies.

---

### **5️⃣ Category Ratings by City**
- **Question:** What are the average, minimum, and maximum ratings for each category in each city?
- **Purpose:** Evaluate regional differences in product satisfaction to tailor localized marketing and merchandising strategies.

---

### **6️⃣ Total Profit by Category**
- **Question:** What is the total profit generated by each category, ranked from highest to lowest?
- **Purpose:** Highlight high-performing categories to guide pricing, promotion, and product expansion decisions.

---

### **7️⃣ Most Common Payment Method Per Branch**
- **Question:** Which payment method is used most frequently in each branch?
- **Purpose:** Understand branch-level customer payment trends and optimize financial processing or payment offers.

---

### **8️⃣ Sales Trends by Daily Shift**
- **Question:** How many transactions occur during Morning, Afternoon, and Evening shifts across branches?
- **Purpose:** Assist in planning workforce scheduling, stock replenishment, and promotional timing.

---

### **9️⃣ Year-over-Year Revenue Decline**
- **Question:** Which branches experienced the largest drop in revenue compared to the previous year?
- **Purpose:** Detect underperforming locations, diagnose potential issues, and support turnaround strategies.







**1️⃣ Payment Methods & Sales Analysis**
- **Question:** What payment methods were used, and how many transactions and items were sold using each?


select
	w.payment_method ,
	count(*) as total_transactions,
	SUM(w.quantity) as total_quantity
from
	walmart w
group by
	payment_method;




--### **2️⃣ Highest Rated Category by Branch**
--- **Question:** Which product category received the highest average customer rating in each branch?

select
	t.category ,
	t.branch ,
	t.avg_rating
from
	(
	select
		w.branch,
		w.category ,
		round(AVG(w.rating)::numeric, 2) as avg_rating,
		dense_rank() over(partition by w.branch order by AVG(w.rating) desc ) as ranking
	from
		walmart w
	group by
		branch,
		category
) as t
where
	t.ranking = 1 ;




--### **3️⃣ Busiest Day per Branch**
--- **Question:** What day of the week sees the highest transaction volume in each branch?

select
	t.branch,
	t.day_of_month,
	t.total_transaction
from
	(
	select
		w.branch,
		to_char(w."date"::date , 'Day') as day_of_month,
		count(*) total_transaction,
		rank() over(partition by w.branch order by count(*) desc) as ranking
	from
		walmart w
	group by
		1,
		2
) as t
where
	t.ranking = 1 ;





--
--### **4️⃣ Quantity Sold by Payment Method**
--- **Question:** How many total items were purchased using each payment method?


select
	w.payment_method ,
	SUM(w.quantity) total_item_per
from
	walmart w
group by
	payment_method ;



--### **5️⃣ Category Ratings by City**
--- **Question:** What are the average, minimum, and maximum ratings for each category in each city?

select
	w.city,
	w.category , 
	MAX(w.rating) max_rating,
	MIN(w.rating) min_rating ,
	round(AVG(w.rating)::numeric, 2) avg_rating
from
	walmart w
group by
	city,
	category
order by
	1,
	2;



--### **6️⃣ Total Profit by Category**
--- **Question:** What is the total profit generated by each category, ranked from highest to lowest?

select
	w.category ,
	round(SUM(w.total)::numeric, 2) total_profit
from
	walmart w
group by
	category
order by
	total_profit desc;


--### **7️⃣ Most Common Payment Method Per Branch**
--- **Question:** Which payment method is used most frequently in each branch?


select
	t.branch,
	t.payment_method,
	t.total_payments
from
	(
	select
		w.branch,
		w.payment_method,
		count(*) as total_payments,
		rank() over(partition by w.branch order by count(*) desc) as ranking
	from
		walmart w
	group by
		branch ,
		w.payment_method 
) as t
where
	ranking = 1 ;




--**8️⃣ Sales Trends by Daily Shift**
--- **Question:** How many transactions occur during Morning, Afternoon, and Evening shifts across branches?



select
	w.branch ,
	sum(case when extract(hour from w.time::time)<12 then 1 else 0 end ) as morning_transactions,
	sum(case when extract(hour from w.time::time) between 12 and 17 then 1 else 0 end ) as Afternoon_transactions,
	sum(case when extract(hour from w.time::time)>17 then 1 else 0 end ) as Evening_transactions
from
	walmart w
group by
	w.branch
order by
	w.branch ;


--**9️⃣ Year-over-Year Revenue Decline**
--- **Question:** Which branches experienced the largest drop in revenue compared to the previous year?

with current_year_rev as (
select
	w.branch ,
	sum (w.total) as current_year_rev
from
	walmart w
where
	extract(year from w."date"::Date) = 2023
group by
	w.branch
),
prev_year_rev as (
select
	w.branch ,
	sum (w.total) as prev_year_rev
from
	walmart w
where
	extract(year from w."date"::Date) = 2022
group by
	w.branch
)
select
	c.branch ,
	c.current_year_rev ,
	p.prev_year_rev ,
	round((p.prev_year_rev - c.current_year_rev)::numeric / p.prev_year_rev::numeric * 100, 2) as revenue_diff
from
	current_year_rev as c
join prev_year_rev as p
on
	c.branch = p.branch
order by
	revenue_diff;

